name = "mctc-gcp"
version = "2.3.1"
license = "LGPL-3.0-or-later"
maintainer = ["@grimme-lab"]
author = ["Stefan Grimme", "J. Gerit Brandenburg", "Holger Kruse"]
copyright = "2012-2021 Grimme group"
description = "Geometrical Counter-Poise correction"
keywords = ["counterpoise", "computational-chemistry"]

[dependencies]
[dependencies.mctc-lib]
git = "https://github.com/grimme-lab/mctc-lib"
tag = "v0.2.0"

[dev-dependencies]
[dev-dependencies.mstore]
git = "https://github.com/grimme-lab/mstore"
tag = "v0.1.1"

[[executable]]
name = "mctc-gcp"
main = "main.f90"
source-dir = "app"
